const SET_PLAYLIST_REC = 'SET_PLAYLIST_REC'
const SET_NEWSONG_REC = 'SET_NEWSONG_REC'
const SET_NEWALBUM_REC = 'SET_NEWALBUM_REC'
const SET_NEWRANK_REC = 'SET_NEWRANK_REC'
const SET_NEWMV_REC = 'SET_NEWMV_REC'

export {
  SET_PLAYLIST_REC,
  SET_NEWSONG_REC,
  SET_NEWALBUM_REC,
  SET_NEWRANK_REC,
  SET_NEWMV_REC
}