//用户登录状态
const SET_USER_LOGIN_STATUS = 'SET_USER_LOGIN_STATUS'
//控制登录盒子显示隐藏
const SHOW_LOGIN_BOX = 'SHOW_LOGIN_BOX'
//已登录用户信息
const SET_USER_INFO = 'SET_USER_INFO'
export { SHOW_LOGIN_BOX, SET_USER_LOGIN_STATUS, SET_USER_INFO }
