const SET_CURRENTMUSIC = 'SET_CURRENTMUSIC'
const SET_MUSIC_STATUS = 'SET_MUSIC_STATUS'
const SET_CURRENT_MUSIC_LYRIC = 'SET_CURRENT_MUSIC_LYRIC'
const SET_CURRENT_MUSIC_ID = 'SET_CURRENT_MUSIC_ID'

export {
  SET_CURRENTMUSIC,
  SET_MUSIC_STATUS,
  SET_CURRENT_MUSIC_LYRIC,
  SET_CURRENT_MUSIC_ID
}
