const SET_CURRENT_MUSIC = 'SET_CURRENT_MUSIC'
const SET_MUSIC_STATUS = 'SET_MUSIC_STATUS'
const SET_CURRENT_MUSIC_ID = 'SET_CURRENT_MUSIC_ID'
export {
  SET_CURRENT_MUSIC,
  SET_MUSIC_STATUS,
  SET_CURRENT_MUSIC_ID
}
