const SET_CURRENTMUSIC = 'SET_CURRENTMUSIC'
const SET_MUSIC_STATUS = 'SET_MUSIC_STATUS'
const SET_CURRENTMUSICLYRIC = 'SET_CURRENTMUSICLYRIC'

export { SET_CURRENTMUSIC, SET_MUSIC_STATUS, SET_CURRENTMUSICLYRIC }
