//设置推荐歌手
const SET_SINGER_REC = 'SET_SINGER_REC'
//设置热门歌手
const SET_HOTSINGER_REC = 'SET_HOTSINGER_REC'
//设置关注歌手
const SET_COLLECT_SINGER = 'SET_COLLECT_SINGER'
export { SET_SINGER_REC, SET_HOTSINGER_REC, SET_COLLECT_SINGER }
